### PR TITLE
Prefix 0 to folder names for 2023 AoC to make sort more intuitive and…

### PR DESCRIPTION
**Pull request by verulian**
… consistent. Listings are out of order in many cases without having the added 0 for 1-9.

### CODE REVIEW

**Comment by spytheman** [comment]
The folders for the previous years's days, do not have 0 prefixes.
If you want consistency, you will have to rename their folders as well.

**Comment by verulian** [comment]
I think I have done as requested for previous years now.

**Comment by Le0Developer** [comment]
You should rebase on current main branch to resolve the merge conflicts

**Comment by spytheman** [comment]
(rebased over main)

**Comment by Le0Developer** [comment]
`leodev.v` and `code.input` of today need to be moved into the new directory

**Review by Le0Developer — APPROVED** [review]
LGTM

**Comment by spytheman** [comment]
LGTM too. I am still waiting for the local `v run verify.v` to pass (the CI is extremely delayed this evening), and if it does, I'll merge it.

**Comment by spytheman** [comment]
wow, it took a little over 30s for compilation, and over 4 minutes for everything to run:
```
Total compilation time:  36830 ms ; Total running time: 250925 ms
```

**Pull request merged**
